# .github/workflows/douban.yml
name: douban
on:
  push:
    branches:
      - main
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 171320005
        type: movie
        format: csv
        dir: ./douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 171320005
        type: book
        format: csv
        dir: ./douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './douban'
